services:
  - type: web
    name: lwasiva-net-api
    env: node
    plan: free
    buildCommand: npm install && npm run frontend:build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: mysql-a72aeaf-sagelusenge-7c93.a.aivencloud.com
      - key: DB_PORT
        value: 18531
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: WHATSAPP_ENABLED
        value: "false"
      - key: WHATSAPP_PROVIDER
        value: meta
      - key: WHATSAPP_FROM_NUMBER
        value: "243980208012"

  - type: static
    name: lwasiva-net-web
    buildCommand: npm install && npm run frontend:build
    staticPublishPath: dist/frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: https://lwasiva-net-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
